language: php
php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer update
  - npm install karma
  - npm install jasmine-core

script:
  - php -d display_errors=On vendor/bin/phpunit --configuration phpunit.xml --testsuite unit --exclude-group ignore
  - karma start --single-run --browsers Chrome karma.conf.js