language: php
php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer update
  - composer install --prefer-source --no-interaction --dev

script: php -d display_errors=On vendor/bin/phpunit --configuration phpunit.xml --testsuite unit --exclude-group ignore
