language: php
php:
  - 5.6

before_script:
  - cp .travis.env .env
  - composer update
  - composer install --prefer-source --no-interaction --dev
  - npm install karma
  - npm install jasmine-core
  - npm install karma-jasmine --save-dev
  - npm install phantomjs-prebuilt
  - npm install karma-phantomjs-launcher --save-dev

script:
  - php -d memory_limit=2048M -d display_errors=On vendor/bin/phpunit --configuration phpunit.xml --testsuite unit --exclude-group ignore
  - karma start --single-run --browsers PhantomJS karma.conf.js