db-bibliomania:
  image: mysql:5.7
  ports:
   - "3306:3306"
  command: mysqld --sql_mode="" --skip-name-resolve
  environment:
        MYSQL_ROOT_PASSWORD: test
        MYSQL_DATABASE: BiblioMania
        MYSQL_USER: test
        MYSQL_PASSWORD: test

smtp:
  image: djfarrelly/maildev
  ports:
    - "1080:80"
    - "1025:25"