version: '2'
services:
    bibliomania-elasticsearch:
        container_name: bibliomania-elasticsearch
        image: bibliomania-elasticsearch:latest
        ports:
            - 9200:9200
            - 9300:9300