<?php

class CountrySeeder extends Seeder {

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		DB::statement("INSERT INTO country(id, code, name) VALUES (1, 'US', 'United States')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (2, 'CA', 'Canada')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (3, 'AF', 'Afghanistan')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (4, 'AL', 'Albania')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (5, 'DZ', 'Algeria')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (6, 'DS', 'American Samoa')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (7, 'AD', 'Andorra')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (8, 'AO', 'Angola')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (9, 'AI', 'Anguilla')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (10, 'AQ', 'Antarctica')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (11, 'AG', 'Antigua and/or Barbuda')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (12, 'AR', 'Argentina')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (13, 'AM', 'Armenia')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (14, 'AW', 'Aruba')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (15, 'AU', 'Australia')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (16, 'AT', 'Austria')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (17, 'AZ', 'Azerbaijan')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (18, 'BS', 'Bahamas')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (19, 'BH', 'Bahrain')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (20, 'BD', 'Bangladesh')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (21, 'BB', 'Barbados')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (22, 'BY', 'Belarus')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (23, 'BE', 'Belgium')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (24, 'BZ', 'Belize')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (25, 'BJ', 'Benin')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (26, 'BM', 'Bermuda')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (27, 'BT', 'Bhutan')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (28, 'BO', 'Bolivia')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (29, 'BA', 'Bosnia and Herzegovina')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (30, 'BW', 'Botswana')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (31, 'BV', 'Bouvet Island')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (32, 'BR', 'Brazil')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (33, 'IO', 'British lndian Ocean Territory')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (34, 'BN', 'Brunei Darussalam')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (35, 'BG', 'Bulgaria')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (36, 'BF', 'Burkina Faso')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (37, 'BI', 'Burundi')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (38, 'KH', 'Cambodia')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (39, 'CM', 'Cameroon')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (40, 'CV', 'Cape Verde')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (41, 'KY', 'Cayman Islands')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (42, 'CF', 'Central African Republic')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (43, 'TD', 'Chad')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (44, 'CL', 'Chile')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (45, 'CN', 'China')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (46, 'CX', 'Christmas Island')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (47, 'CC', 'Cocos (Keeling) Islands')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (48, 'CO', 'Colombia')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (49, 'KM', 'Comoros')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (50, 'CG', 'Congo')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (51, 'CK', 'Cook Islands')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (52, 'CR', 'Costa Rica')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (53, 'HR', 'Croatia (Hrvatska)')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (54, 'CU', 'Cuba')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (55, 'CY', 'Cyprus')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (56, 'CZ', 'Czech Republic')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (57, 'DK', 'Denmark')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (58, 'DJ', 'Djibouti')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (59, 'DM', 'Dominica')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (60, 'DO', 'Dominican Republic')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (61, 'TP', 'East Timor')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (62, 'EC', 'Ecuador')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (63, 'EG', 'Egypt')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (64, 'SV', 'El Salvador')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (65, 'GQ', 'Equatorial Guinea')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (66, 'ER', 'Eritrea')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (67, 'EE', 'Estonia')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (68, 'ET', 'Ethiopia')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (69, 'FK', 'Falkland Islands (Malvinas)')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (70, 'FO', 'Faroe Islands')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (71, 'FJ', 'Fiji')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (72, 'FI', 'Finland')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (73, 'FR', 'France')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (74, 'FX', 'France, Metropolitan')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (75, 'GF', 'French Guiana')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (76, 'PF', 'French Polynesia')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (77, 'TF', 'French Southern Territories')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (78, 'GA', 'Gabon')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (79, 'GM', 'Gambia')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (80, 'GE', 'Georgia')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (81, 'DE', 'Germany')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (82, 'GH', 'Ghana')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (83, 'GI', 'Gibraltar')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (84, 'GR', 'Greece')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (85, 'GL', 'Greenland')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (86, 'GD', 'Grenada')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (87, 'GP', 'Guadeloupe')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (88, 'GU', 'Guam')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (89, 'GT', 'Guatemala')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (90, 'GN', 'Guinea')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (91, 'GW', 'Guinea-Bissau')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (92, 'GY', 'Guyana')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (93, 'HT', 'Haiti')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (94, 'HM', 'Heard and Mc Donald Islands')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (95, 'HN', 'Honduras')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (96, 'HK', 'Hong Kong')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (97, 'HU', 'Hungary')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (98, 'IS', 'Iceland')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (99, 'IN', 'India')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (100, 'ID', 'Indonesia')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (101, 'IR', 'Iran (Islamic Republic of)')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (102, 'IQ', 'Iraq')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (103, 'IE', 'Ireland')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (104, 'IL', 'Israel')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (105, 'IT', 'Italy')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (106, 'CI', 'Ivory Coast')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (107, 'JM', 'Jamaica')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (108, 'JP', 'Japan')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (109, 'JO', 'Jordan')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (110, 'KZ', 'Kazakhstan')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (111, 'KE', 'Kenya')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (112, 'KI', 'Kiribati')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (113, 'KP', 'Korea, Democratic People''s Republic of')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (114, 'KR', 'Korea, Republic of')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (115, 'XK', 'Kosovo')");

		DB::statement("INSERT INTO country(id, code, name) VALUES (116, 'KW', 'Kuwait')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (117, 'KG', 'Kyrgyzstan')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (118, 'LA', 'Lao People''s Democratic Republic')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (119, 'LV', 'Latvia')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (120, 'LB', 'Lebanon')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (121, 'LS', 'Lesotho')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (122, 'LR', 'Liberia')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (123, 'LY', 'Libyan Arab Jamahiriya')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (124, 'LI', 'Liechtenstein')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (125, 'LT', 'Lithuania')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (126, 'LU', 'Luxembourg')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (127, 'MO', 'Macau')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (128, 'MK', 'Macedonia')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (129, 'MG', 'Madagascar')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (130, 'MW', 'Malawi')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (131, 'MY', 'Malaysia')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (132, 'MV', 'Maldives')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (133, 'ML', 'Mali')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (134, 'MT', 'Malta')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (135, 'MH', 'Marshall Islands')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (136, 'MQ', 'Martinique')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (137, 'MR', 'Mauritania')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (138, 'MU', 'Mauritius')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (139, 'TY', 'Mayotte')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (140, 'MX', 'Mexico')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (141, 'FM', 'Micronesia, Federated States of')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (142, 'MD', 'Moldova, Republic of')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (143, 'MC', 'Monaco')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (144, 'MN', 'Mongolia')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (145, 'ME', 'Montenegro')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (146, 'MS', 'Montserrat')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (147, 'MA', 'Morocco')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (148, 'MZ', 'Mozambique')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (149, 'MM', 'Myanmar')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (150, 'NA', 'Namibia')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (151, 'NR', 'Nauru')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (152, 'NP', 'Nepal')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (153, 'NL', 'Netherlands')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (154, 'AN', 'Netherlands Antilles')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (155, 'NC', 'New Caledonia')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (156, 'NZ', 'New Zealand')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (157, 'NI', 'Nicaragua')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (158, 'NE', 'Niger')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (159, 'NG', 'Nigeria')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (160, 'NU', 'Niue')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (161, 'NF', 'Norfork Island')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (162, 'MP', 'Northern Mariana Islands')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (163, 'NO', 'Norway')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (164, 'OM', 'Oman')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (165, 'PK', 'Pakistan')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (166, 'PW', 'Palau')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (167, 'PA', 'Panama')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (168, 'PG', 'Papua New Guinea')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (169, 'PY', 'Paraguay')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (170, 'PE', 'Peru')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (171, 'PH', 'Philippines')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (172, 'PN', 'Pitcairn')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (173, 'PL', 'Poland')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (174, 'PT', 'Portugal')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (175, 'PR', 'Puerto Rico')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (176, 'QA', 'Qatar')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (177, 'RE', 'Reunion')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (178, 'RO', 'Romania')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (179, 'RU', 'Russian Federation')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (180, 'RW', 'Rwanda')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (181, 'KN', 'Saint Kitts and Nevis')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (182, 'LC', 'Saint Lucia')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (183, 'VC', 'Saint Vincent and the Grenadines')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (184, 'WS', 'Samoa')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (185, 'SM', 'San Marino')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (186, 'ST', 'Sao Tome and Principe')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (187, 'SA', 'Saudi Arabia')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (188, 'SN', 'Senegal')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (189, 'RS', 'Serbia')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (190, 'SC', 'Seychelles')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (191, 'SL', 'Sierra Leone')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (192, 'SG', 'Singapore')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (193, 'SK', 'Slovakia')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (194, 'SI', 'Slovenia')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (195, 'SB', 'Solomon Islands')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (196, 'SO', 'Somalia')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (197, 'ZA', 'South Africa')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (198, 'GS', 'South Georgia South Sandwich Islands')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (199, 'ES', 'Spain')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (200, 'LK', 'Sri Lanka')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (201, 'SH', 'St. Helena')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (202, 'PM', 'St. Pierre and Miquelon')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (203, 'SD', 'Sudan')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (204, 'SR', 'Suriname')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (205, 'SJ', 'Svalbarn and Jan Mayen Islands')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (206, 'SZ', 'Swaziland')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (207, 'SE', 'Sweden')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (208, 'CH', 'Switzerland')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (209, 'SY', 'Syrian Arab Republic')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (210, 'TW', 'Taiwan')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (211, 'TJ', 'Tajikistan')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (212, 'TZ', 'Tanzania, United Republic of')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (213, 'TH', 'Thailand')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (214, 'TG', 'Togo')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (215, 'TK', 'Tokelau')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (216, 'TO', 'Tonga')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (217, 'TT', 'Trinidad and Tobago')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (218, 'TN', 'Tunisia')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (219, 'TR', 'Turkey')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (220, 'TM', 'Turkmenistan')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (221, 'TC', 'Turks and Caicos Islands')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (222, 'TV', 'Tuvalu')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (223, 'UG', 'Uganda')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (224, 'UA', 'Ukraine')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (225, 'AE', 'United Arab Emirates')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (226, 'GB', 'United Kingdom')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (227, 'UM', 'United States minor outlying islands')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (228, 'UY', 'Uruguay')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (229, 'UZ', 'Uzbekistan')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (230, 'VU', 'Vanuatu')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (231, 'VA', 'Vatican City State')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (232, 'VE', 'Venezuela')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (233, 'VN', 'Vietnam')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (234, 'VG', 'Virgin Islands (British)')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (235, 'VI', 'Virgin Islands (U.S.)')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (236, 'WF', 'Wallis and Futuna Islands')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (237, 'EH', 'Western Sahara')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (238, 'YE', 'Yemen')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (239, 'YU', 'Yugoslavia')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (240, 'ZR', 'Zaire')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (241, 'ZM', 'Zambia')");
		DB::statement("INSERT INTO country(id, code, name) VALUES (242, 'ZW', 'Zimbabwe')");
	}

}